version: '3'
services:
  socat:
    image: alpine/socat
    command: TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:/tmp/.X11-unix/X0
    ports:
      - "6000:6000"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=host.docker.internal:6000
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - socat
